<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$_config  = $this->helper('Sm\Autostore\Helper\Data');
$tabStyle = $_config->getProductDetail('tab_style');

$show_custom_tab   = $_config->getProductDetail('show_custom_tab');
$custom_tab_name   = $_config->getProductDetail('custom_tab_name');
$customtab_content = $_config->getProductDetail('customtab_content');

/*获取video faq内容*/
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')): ?>
    <div class="product info detailed sticky">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items <?php echo $tabStyle . '-style' ?>"
             data-mage-init='{"tabs":{"openedState":"active", "collapsible": true, "active": false, "multipleCollapsible": true}}'>
            <?php if ($tabStyle == "default" || $tabStyle == "vertical") { ?>
                <ul class="resp-tabs-list">
                    <?php foreach ($detailedInfoGroup as $name): ?>
                        <?php
                        $html = $layout->renderElement($name);
                        if (!trim($html)) {
                            continue;
                        }
                        $alias = $layout->getElementAlias($name);
                        $label = $block->getChildData($alias, 'title');
                        ?>
                        <li class="data item title"
                            aria-labeledby="tab-label-<?= /* @escapeNotVerified */
                            $alias ?>-title"
                            data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */
                        $alias ?>">
                            <a class="data switch"
                               tabindex="-1"
                               data-toggle="switch"
                               href="#<?= /* @escapeNotVerified */
                               $alias ?>"
                               id="tab-label-<?= /* @escapeNotVerified */
                               $alias ?>-title">
                                <?= /* @escapeNotVerified */
                                $label ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                    <?php if ($show_custom_tab) { ?>
                        <li id="tab-label-customtab" class="data item title" aria-labeledby="tab-label-customtab-title"
                            data-role="collapsible" role="tab" data-collapsible="true"
                            aria-controls="product.info.customtab" aria-selected="false" aria-expanded="true"
                            tabindex="0">
                            <a class="data switch"
                               tabindex="-1"
                               data-toggle="switch"
                               href="#<?= /* @escapeNotVerified */
                               $alias ?>"
                               id="tab-label-<?= /* @escapeNotVerified */
                               $alias ?>-title">
                                <?php echo $custom_tab_name ?>
                            </a>
                        </li>
                    <?php } ?>
                    <!--videos-->
                    <?php if($product->getResource()->getAttribute('video')->getFrontend()->getValue($product)) { ?>
                    <li id="tab-label-videos" class="data item title" aria-labeledby="tab-label-videos-title"
                            data-role="collapsible" role="tab" data-collapsible="true"
                            aria-controls="product.info.customtab" aria-selected="false" aria-expanded="true"
                            tabindex="0">
                            <a class="data switch"
                               tabindex="-1"
                               data-toggle="switch"
                               href="#videos"
                               id="tab-label-videos-title">
                                Videos
                            </a>
                    </li>
                    <?php } ?>
                    <!--faq-->
                    <?php if($product->getResource()->getAttribute('faq')->getFrontend()->getValue($product)) { ?>
                    <li id="tab-label-faq" class="data item title" aria-labeledby="tab-label-faq-title"
                            data-role="collapsible" role="tab" data-collapsible="true"
                            aria-controls="product.info.customtab" aria-selected="false" aria-expanded="true"
                            tabindex="0">
                            <a class="data switch"
                               tabindex="-1"
                               data-toggle="switch"
                               href="#faq"
                               id="tab-label-faq-title">
                                Faq
                            </a>
                    </li>
                    <?php } ?>
                </ul>
                
                

                <div class="resp-tabs-container">
                    <?php foreach ($detailedInfoGroup as $name): ?>
                        <?php
                        $html = $layout->renderElement($name);
                        if (!trim($html)) {
                            continue;
                        }
                        $alias = $layout->getElementAlias($name);
                        $label = $block->getChildData($alias, 'title');
                        ?>

                        <div class="data item content resp-tab-content" id="<?= /* @escapeNotVerified */
                        $alias ?>" data-role="content">
                            <?= /* @escapeNotVerified */
                            $html ?>
                        </div>
                    <?php endforeach; ?>
                    <?php if ($show_custom_tab) { ?>
                        <div class="data item content resp-tab-content" id="customtab" data-role="content">
                            <?php
                            echo $customtab_content;
                            ?>
                        </div>
                    <?php } ?>
                </div>
            <?php } else { ?>
                <?php foreach ($detailedInfoGroup as $name): ?>
                    <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html) || $layout->getElementAlias($name) == "additional" || $layout->getElementAlias($name) == "productinquiry.form" || $layout->getElementAlias($name) == "reviews") {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                    ?>
                    <h2 class="data item title resp-accordion"
                        aria-labeledby="tab-label-<?= /* @escapeNotVerified */
                        $alias ?>-title"
                        data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */
                    $alias ?>">
                        <a class="data switch"
                           tabindex="-1"
                           data-toggle="switch"
                           href="#<?= /* @escapeNotVerified */
                           $alias ?>"
                           id="tab-label-<?= /* @escapeNotVerified */
                           $alias ?>-title">
                            <?= /* @escapeNotVerified */
                            $label ?>
                        </a>
                    </h2>

                    <div class="data item content resp-tab-content" id="<?= /* @escapeNotVerified */
                    $alias ?>" data-role="content">
                        <?= /* @escapeNotVerified */
                        $html ?>
                    </div>
                <?php endforeach; ?>
                <?php if ($show_custom_tab) { ?>
                    <h2 id="tab-label-customtab" class="data item title resp-accordion"
                        aria-labeledby="tab-label-customtab-title" data-role="collapsible" role="tab"
                        data-collapsible="true" aria-controls="product.info.customtab" aria-selected="false"
                        aria-expanded="true" tabindex="0">
                        <a class="data switch"
                           tabindex="-1"
                           data-toggle="switch"
                           href="#<?= /* @escapeNotVerified */
                           $alias ?>"
                           id="tab-label-<?= /* @escapeNotVerified */
                           $alias ?>-title">
                            <?php echo $custom_tab_name ?>
                        </a>
                    </h2>
                    <div class="data item content resp-tab-content" id="customtab" data-role="content">
                        <?php
                        echo $customtab_content;
                        ?>
                    </div>
                <?php } ?>
            <?php } ?>
                    
                    <!--videos-->
                    <?php if($product->getResource()->getAttribute('video')->getFrontend()->getValue($product)) { ?>
                    <li id="tab-label-videos" class="data item title resp-accordion" aria-labeledby="tab-label-videos-title"
                            data-role="collapsible" role="tab" data-collapsible="true"
                            aria-controls="product.info.customtab" aria-selected="false" aria-expanded="true"
                            tabindex="0">
                            <a class="data switch"
                               tabindex="-1"
                               data-toggle="switch"
                               href="#videos"
                               id="tab-label-videos-title">
                                Videos
                            </a>
                    </li>
                    <?php } ?>
                     <?php if($product->getResource()->getAttribute('video')->getFrontend()->getValue($product)) { ?>
                    <div class="data item content resp-tab-content" id="videos" data-role="content">
                        <?php
                            echo $product->getResource()->getAttribute('video')->getFrontend()->getValue($product);
                        ?>
                    </div>
                    <?php } ?>
                    <!--faq-->
                    <?php if($product->getResource()->getAttribute('faq')->getFrontend()->getValue($product)) { ?>
                    <li id="tab-label-faq" class="data item title resp-accordion" aria-labeledby="tab-label-faq-title"
                            data-role="collapsible" role="tab" data-collapsible="true"
                            aria-controls="product.info.customtab" aria-selected="false" aria-expanded="true"
                            tabindex="0">
                            <a class="data switch"
                               tabindex="-1"
                               data-toggle="switch"
                               href="#faq"
                               id="tab-label-faq-title">
                                Shipping & Return
                            </a>
                    </li>
                    <?php } ?>
                    <?php if($product->getResource()->getAttribute('faq')->getFrontend()->getValue($product)) { ?>
                    <div class="data item content resp-tab-content" id="faq" data-role="content">
                        <?php
                            echo $product->getResource()->getAttribute('faq')->getFrontend()->getValue($product);
                        ?>
                    </div>
                    <?php } ?>

        </div>
    </div>
<?php endif; ?>
<script type="text/javascript">
        //             require([
        //                 'jquery'
        //             ], function ($) {
        //                 $(document).ready(function(){
        //                     var sticky_tabs;
        //                     var is_sticky = false;
        //                     $(window).scroll(function(){
        //                         if($(window).scrollTop() >= $(".product.info.detailed").offset().top-50){
        //                             if(!is_sticky){
        //                                 $(".product.info.detailed.sticky").before('<div class="product-tabs-container"><div class="container"></div></div>');
        //                                 $(".product.info.detailed.sticky .resp-tabs-list").each(function(){
        //                                     $(".product-tabs-container > .container").append($(this).clone().detach());
        //                                 });
        //                                 $(".product-tabs-container a").click(function(){
        //                                         var bid = getCaption(this.href);
        //                                         /*冻结页签 点击显示/隐藏*/
        //                                         $("#description").css('display','none');
        //                                         $("#description").attr({"aria-expanded": "false","aria-hidden": "true"});
        //                                         //alert("description");
        //                                         $("#additional").css('display','none');
        //                                         $("#additional").attr({"aria-expanded": "false","aria-hidden": "true"});
        //                                         //alert("additional");
        //                                         $("#reviews").css('display','none');
        //                                         $("#reviews").attr({"aria-expanded": "false","aria-hidden": "true"});
        //                                         //alert("reviews");
        //                                         $("#questions").css('display','none');
        //                                         $("#questions").attr({"aria-expanded": "false","aria-hidden": "true"});
        //                                         //alert("questions");
        //                                         $("[id='productinquiry.form']").css('display','none');
        //                                         $("[id='productinquiry.form']").attr({"aria-expanded": "false","aria-hidden": "true"});
        //                                         //alert("productinquiry");
        //                                         $("#videos").css('display','none');
        //                                         $("#videos").attr({"aria-expanded": "false","aria-hidden": "true"});
        //                                         //alert("videos");
        //                                         $("#faq").css('display','none');
        //                                         $("#faq").attr({"aria-expanded": "false","aria-hidden": "true"});
        //                                         //alert("faq");
        //                                         $("[id='" + bid + "']").css('display','block');
        //                                         $("[id='" + bid + "']").attr({"aria-expanded": "true","aria-hidden": "false"});
        //                                         //alert(bid);
        //                                     }
        //                                 );
        //                                 <?php if (1): ?>
        //                                 $(".product-tabs-container").addClass("has-sticky-header");
        //                                 <?php endif; ?>
        //                                 is_sticky = true;
        //                             }
        //                         } else {
        //                             $(".product-tabs-container").remove();
								// 	$(".cart-sticky").removeClass("cart-sticky-header");
        //                             is_sticky = false;
        //                         }
        //                     });
        //                 });
                        
        //                 function getCaption(obj){
        //                     var index=obj.lastIndexOf("\#");
        //                     obj=obj.substring(index+1,obj.length);
        //                     // console.log(obj);
        //                     return obj;
        //                 };
        //             }
        //             );
                </script>
<style>
.product-tabs-container.has-sticky-header {
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    padding: 15px 0;
    z-index: 3;
    background-color: #fff;
    box-shadow: 0 1px 2px rgb(0 0 0 / 10%);
    text-align: left;
    z-index: 9999999;
}
.product.data.items {
    margin-bottom: 0 !important;
    padding-top: 0 !important;
    padding-bottom: 0px !important;
    border-bottom: unset !important;
}
.fieldset:last-child {
    margin-bottom: 0px !important;
}
#product-addtocart-button {
    margin-bottom: 0px !important;
}
.review-list-ez .review-item-col-main{
    width: 100% !important;
}
#product-review-container .block-title {
    text-align: center !important;
    font-size: 25px !important;
}
#product-review-container .rating-summary {
    text-align: center !important;
    font-size: 16px;
}
.soldtogether-block .amazonstyle-images {
    width: 100%;
    overflow: auto;
    overflow-x: auto;
    display: -webkit-flex;
}
.toolbar .pages{display:block !important}
.review-toolbar .pages{
    border-bottom: unset !important;
    padding:unset !important;
}
.product-payment{top: 0 !important;}
.likes-tips {
    display: none !important;
}
.rating-summary span{width:100% !important;}
.review-add-ez .review-form-actions{padding-left: 0 !important;}   
.product-tabs-container .item.title{display: inline-block; padding: 0 10px; font-size: 18px;}
.product.data.items > .item.content{margin-left: 0px;}
.review-add-ez .block-title strong{color: #000;}
.product-tabs-container .item.title #tab-label-reviews-title span.counter:before{content: "(";}
.product-tabs-container .item.title #tab-label-reviews-title span.counter:after{content: ")";}
.actions.cart-sticky.cart-sticky-header{position: fixed; top: 0; right: 0; margin-top: 4px !important; z-index: 99999;}
.actions.cart-sticky.cart-sticky-header #buy-on-amazon{display:none;}
.cart-sticky-header #product-addtocart-button{border-radius: 4px;padding: 12px 20px;margin-top: 2px;}
.cart-sticky-header .buynow-button #buy-now{border-radius: 4px; padding: 12px 20px;margin-top: 2px;}

.product-tabs-container.has-sticky-header{padding: 5px 0;min-height: 40px;}
.product-tabs-container .item.title a{padding: 0 3px;}
.footer-panel{padding-bottom: 100px;}

@media (min-width: 768px) {
.has-sticky-header .container{max-width: 768px;}
.product.data.items > div.item.content{padding-top: 70px; padding-bottom: 0px; margin: 0px;border-top: none;}
.product.data.items #description{margin-top: -50px;}
.product.attribute.description{border-top: 2px solid #e7e7e6; padding-top: 20px;}
.product-block-title h2{margin-top: 0px;}
.product-block-title{border-top: 5px solid rgb(66, 139, 202); padding-top: 20px;}
.review-form-actions{padding-left: 0 !important;}
 


#product-addtocart-button{width: 140px;}
.buynow-button{width: 140px !important;}
.paypal-button.paypal-button-context-iframe{margin-top: 4px;}

.actions.cart-sticky.cart-sticky-header{width: 100% !important;background: #fff;top: 50px;}
.actions.cart-sticky.cart-sticky-header #product-addtocart-button{width: 260px;margin-left: 12%;}
.actions.cart-sticky.cart-sticky-header .buynow-button{width: 260px !important;}
.actions.cart-sticky.cart-sticky-header .paypal-button.paypal-button-context-iframe{width: 160px !important;height: 45px !important;margin-top: -2px;}

.soldtogether-block.amazon-stripe .block-content{display: inline-block;}
}
/*mobile css*/

@media (max-width: 476px){
.cart-qty{display: contents;}
.product-wrap .box-tocart .field.qty .control input{width: 40%;margin-top: -1px;}
.product-wrap .box-tocart .field.qty .control{width: 50%;}
.pro-pop{width: 45%;margin-bottom: 10px;font-size: 12px;}
.product.data.items > .item.title{border: 1px solid; padding-bottom: 25px; padding-left: 5px; padding-right: 5px;}
.product.data.items > .item.title:before{margin-right: 10px;}
.um-inline label.label{width: 100px;margin-right: 10px; font-size: 12px;}
.um-inline .control{width: 240px;}
.um-primary .submit{width: 240px; margin-left: 110px; display: block;}
.share-span{font-size: 12px !important;margin-right: 5px !important;}
a.at-icon-wrapper.at-share-btn{width: 30px !important; height: 30px !important;}
.at-resp-share-element .at-icon{width: 20px !important; height: 20px !important;}
.product.data.items .data.item td{padding: 0;}

.product.data.items > .item.title{display: none;}
.buynow-button{display: none;}
#product-addtocart-button{width: 345px;margin-right: 1%;padding: 15px 20px;}
.actions.cart-sticky.cart-sticky-header{bottom: 0;top:unset;width: 100% !important;z-index: 5;background: #fff;padding-top: 15px;}
#buy-on-amazon {
    width: 345px !important;
    margin: unset !important;
}
@media (max-width: 540px){
    div#addthis_wrap {
        top: 0 !important;
        right: 0 !important;
    }
    .product-info-main .product-reviews-summary{width: 100%;}
    button, .cart-container .action.continue, a.action.primary, .modal-footer .action-primary.action-accept{
        padding: 0 5px !important;
    }
    .product-item-details {
        border: 1px solid #e5e5e5;
        margin: 0px 0 !important;
    }
    label.product.name.product-item-name {
        display: -webkit-box;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 2;
        overflow: hidden;
    }
    .soldtogether-block {
        padding-top: 20px;
    }
}
.product-tabs-container .item.title {
    font-size: 12px;
    color: #000;
    text-align: center;
    background: #fff;
    margin-right: 1%;
    padding: 0;
}
}
.product-tabs-container.has-sticky-header{padding: 5px 0;background-color: rgb(66, 139, 202);min-height: 40px;}
</style>
<style>
.product-item-details .product-reviews-summary{display: contents !important;}
.products-grid .product-item-info .product-item-details{height:unset !important;}

.load-more {
    margin-top: unset !important;
}
.goodsFAQ_customerTag_Q {
	display: inline-block;
	vertical-align: baseline;
	width: 20px;
	height: 20px;
	line-height: 20px;
	text-align: center;
	font-size: 14px;
	background-color: #266ccc;
	color: #000;
	border-radius: 20px;
	margin-bottom: 20px;
	color:#FFF;
}
.goodsFAQ_customerTag_A{
	display: inline-block;
	vertical-align: baseline;
	width: 20px;
	height: 20px;
	line-height: 20px;
	text-align: center;
	font-size: 14px;
	background-color: #000;
	color: #000;
	border-radius: 20px;
	margin-bottom: 20px;
	color:#FFF;
}
.goodsFAQ_title_Q{
	font-weight: 900;
}
.goodsFAQ_by_Q{
	color:#cacaca;
}
.goodsFAQ_customerGroup {
	border-bottom: 1px solid #eee;
	padding-bottom: 20px;
	margin-bottom: 20px;
}
iframe.iframe_youtube {
    width: 100%;
    height: 328px;
}
@media (max-width: 767px) {
    iframe.iframe_youtube {
        height: 200px;
    }
}
.has-sticky-header .container {
    max-width: 100% !important;
    text-align: center !important;
}
</style>
<script type="text/javascript">
    function show_hide(){
        if(document.getElementById('is_show').style.display == "none")
        {
            document.getElementById('is_show').style.display = "";
            document.getElementById('more-btn').style.display = "none";
            document.getElementById('less-btn').style.display = "";
        }
        else
        {
            document.getElementById('is_show').style.display = "none";
            document.getElementById('more-btn').style.display = "";
            document.getElementById('less-btn').style.display = "none";
        }
    }
</script>

<link href="/pub/media/custom/photoswipe/photoswipe.css" type="text/css" rel="stylesheet" />
<script type="text/javascript" src="/pub/media/custom/photoswipe/klass.min.js"></script>
<script type="text/javascript" src="/pub/media/custom/photoswipe/code.photoswipe-3.0.5.min.js"></script>                
<script>
require(['jquery'], function ($) {
    (function(window, PhotoSwipe){
    		document.addEventListener('DOMContentLoaded', function(){
    			var
    				options = {},
    				//instance = PhotoSwipe.attach( window.document.querySelectorAll('.phg-xg a'), options );
    				instance = PhotoSwipe.attach( window.document.querySelectorAll('.phg-xg'), options );
    		}, false);
    	}(window, window.Code.PhotoSwipe));
});    	
</script>
